language: php
php:
  - 5.4
  - 5.5
  - nightly

env:
  - DB=mysql

before_install:
  - mysql -e 'create database brautoinstalldb;'

install: php install.php --autoinstall

script: ./vendor/bin/atoum -d tests
